### ISSUE TITLE
A suggestion, render_sidemenu feature?

### ISSUE THREAD

**Issue by sunjoomoon** [django-fluent/django-fluent-pages#105]
Do we have the side menu rendering feature? From the doc, I see title, menu, breadcrumb template tag but failed to find side menu tag, normally displayed in the side.

**Comment by vdboor** [comment]
You can render a side menu using the `parent` field. For example:

`{% render_menu parent=page max_depth=1 template="mysite/sidemenymenu.html" %}`

**Comment by sunjoomoon** [comment]
For example, with this 
`Product 
  - IPhone
  - Galaxy
`
If I click `Product` then in the side menu sub menus are shown good as below
`IPhone
-Galaxy
`
However if `IPhone` clicked then side menu shows nothing. Seems it is looking for sub menu.

So my requirements is to show below sub menus with any of `Product` or `IPhone` or `Galaxy` click.
`IPhone
-Galaxy
`
Does that make sense?

**Comment by vdboor** [comment]
Yes it does. Does using `parent=page.parent_id` work for you? I'm not sure how you'd detect whether the item is a child. Would `page.is_leaf_node()` work for you?

**Comment by sunjoomoon** [comment]
Tried above, seems another way of work could be though. Closing this. Thanks.
