### ISSUE TITLE
render_menu doesn't use fallback language

### ISSUE THREAD

**Issue by benkonrath** [django-fluent/django-fluent-pages#112]
I'm using fluent pages for a small section of a site. It's not a multilingual fluent pages site but django's i18n is turned on for the other parts of the site. The default language is English:

```
FLUENT_PAGES_DEFAULT_LANGUAGE_CODE = 'en'
```

Loading the site with a non-English browser (e.g. a Dutch browser), renders the root page but the menus are empty because `render_menu` doesn't use fallback or default language.

I've managed to work around this by wrapping the `render_menu` template tag in a language override:

```
{% load i18n %}

{% language 'en' %}
  {% render_menu ... %}
{% endlanguage %}
```

Is this a bug or is this how `render_menu` is intended to work?

Here are the app versions that I'm using:

```
django==1.8.12
django-polymorphic==0.7.2
django-fluent-pages==0.9
django-fluent-utils==1.2.3
django-parler==1.6.2
django-mptt==0.8.4
django-polymorphic-tree==1.2.4
django-wysiwyg==0.7.1
django-tag-parser==2.1
django-any-urlfield==2.2.1
```

**Comment by vdboor** [comment]
Hi @benkonrath , what are your `PARLER_LANGUAGES` (or `FLUENT_PAGES_LANGUAGES`) and `LANGUAGES` settings? These determine what fallbacks are available.

The fallbacks are used, unless `hide_untranslated_menu_items` is set.

**Comment by benkonrath** [comment]
`LANGUAGES`, `PARLER_LANGUAGES` and `FLUENT_PAGES_LANGUAGES` are all unset so the defaults are being used. Is it required to set these explicitly?

**Comment by vdboor** [comment]
If you want multilingual content to behave (and likely to be administered too), you'll need to configure `LANGUAGES` and `PARLER_LANGUAGES`. This also gives you language tabs in the admin.

When your project is multilingual, but the pages are only entered in english, the `{% language "en" %}` is a good workaround.

FYI, The `FLUENT_PAGES_LANGUAGES` is not needed, it will be generated from `PARLER_LANGUAGES`.

**Comment by benkonrath** [comment]
The fluent pages part of the site isn't a multilingual site which is why nothing is configured. The other parts of the site are multilingual, though, which is why I'm using the default django supplied value for `LANGUAGES`. It feels like this is turning out to be an edge case with my setup so I'm ok with using the`{% language "en" %}` hack.

This was working fine before I upgraded to fluent-pages 1.9 / django 1.8 which is why I filed the issue. Feel free to close it if you don't think it will be investigated or fixed. Thanks for the info.

**Comment by vdboor** [comment]
@benkonrath : it seems your workaround is a good solution for this edge case. In the newer releases there is indeed a bugfix that made sure the menu reflected the language you're seeing.

Also, since everything is multilingual under the hood, the will be a "language code" in the `UrlNode_Translation` model, regardless of whether your project is multilingual or not. In this case, I think it's better to close it unless more issues pop up with non-multilingual projects.

**Comment by benkonrath** [comment]
Ok, thanks for you help.
