### ISSUE TITLE
Version 1.1 uses `native_str` without importing it

### ISSUE THREAD

**Issue by jmurty** [django-fluent/django-fluent-pages#125]
In the recent 1.1 release the `_select_template_name` function in `fluent_pages.adminui.pageadmin` calls the `native_str` function without it being imported in the module, which causes failures with Python version 2.7.12.

Should/could the `native_str` function be imported from `future.utils`?

**Comment by vdboor** [comment]
Thanks for fixing this! I didn't notice this issue yet, and it looks like I've broken it in 2afa7b9da8f66a42cf0c8bab6b01f1ba769b0e39
