### ISSUE TITLE
CMS + multilingual content, broken or feature??

### ISSUE THREAD

**Issue by bashu** [django-fluent/django-fluent-pages#63]
Hi,
I have numerous issues with this fine CMS, after adding new flatpage :

1) two translated pages (eng & german) if I change status for a german page to "draft", english page will also become a draft

2) translation only affects title & slug fields, content is always the same, after I changed german page, english content was lost and overwritten by german

PS: As I can see second _feature_ only affects flatpages and text file types

Here what I have :

``` shell
Django==1.6.11
django-fluent-contents==1.0.1
django-fluent-utils==1.2.1
django-mptt==0.6.0
django-parler==1.4
django-polymorphic==0.7
django-polymorphic-tree==1.1
django-tag-parser==2.1
django-template-analyzer==1.5
django-tinymce==1.5.3
django-wysiwyg==0.7.0
docutils==0.12
future==0.14.3
GDAL==1.11.1
Markdown==2.6.2
Pygments==2.0.2
six==1.9.0
South==1.0
textile==2.2.2
```

**Comment by vdboor** [comment]
Hi! Thanks for reporting this. I see you've been quite active making pull requests, thanks a lot of patching all these little Django 1.8 itches. :+1: 

It seems that I've completely missed updating the "flatpage" and "textfile" types to make that content multilingual as well. :-(
I'd be more then happy to accept a pull request that makes these two apps multilingual as well (and I'll draft one myself later when I have time, but that is currently not the case). The "redirectnode" is a good example how to make this work; and http://django-parler.readthedocs.org/en/latest/advanced/migrating.html describes how to migrate the content.
