### ISSUE TITLE
Serve first page as root page

### ISSUE THREAD

**Issue by bashu** [django-fluent/django-fluent-pages#72]
Right now I need to manually override url to see home page instead of 404 error, this is not very intuitive

![screen shot 2015-05-19 at 10 41 10](https://cloud.githubusercontent.com/assets/144783/7695676/7f09dd6c-fe0c-11e4-8dfa-8a996f2add1d.png)

**Comment by vdboor** [comment]
Summarizing the discussion from the PR:

I'd rather have the admin give some assistence then having a magic behavior.
That would also be unintuitive for other people. Indeed we could do things like:

* expanding the fieldset (and show the tip)
* mark the first top-level page with override_url='/' if there isn't one
* add some checkbox "[x] This is the homepage" and hide the override-url all together.

**Comment by bashu** [comment]
option 2

**Comment by mrmachine** [comment]
I think a "This is the home page" checkbox would be the most intuitive option from a users perspective. It could be shown alongside "Show in navigation" to give it more prominence, and it could automatically unset the option for an existing home page when checked. Perhaps after showing a warning.

"Override URL" seems very technical, and I'm sure many end users won't know or want to care what it means. But everyone knows what a home page is.

The value of the checkbox could be stored on the model, or it could just be aliased to the override URL, so the two can be set interchangeably.

**Comment by vdboor** [comment]
Agreed. By making it a checkbox this setting is also stored on the shared model.
This makes it easier to find the homepage.
When a new translation is added, it should also set the `override_url` to `/` when `is_homepage` is set.
