### ISSUE TITLE
new pypi release

### ISSUE THREAD

**Issue by bashu** [django-fluent/django-fluent-pages#80]
Hey,

Any chance to see 0.9.1 release soon?

**Comment by vdboor** [comment]
Well, the git repo is almost ready. One thing does concern me, the unit tests fail on some Python and Django releases. When this is solved, the 0.9.1 release can be out!

If you have a chance of looking at it, I'd be really grateful.

**Comment by vdboor** [comment]
Release 1.0.1 is out!! :D
