### ISSUE TITLE
PicturePlugin: broken integration

### ISSUE THREAD

**Issue by bashu** [django-fluent/django-fluent-pages#86]
Not sure where to report here or edoburu/django-any-urlfiled, problem is that I can not save URL to a page, see screenshot
![screen shot 2015-08-21 at 15 34 34](https://cloud.githubusercontent.com/assets/144783/9405581/57a3867e-4812-11e5-9c68-27408bc80068.png)

**Comment by bashu** [comment]
Works if selected page ``published``, see ``fluent_pages.forms.fields.PageChoiceField`` 
But the problem is that popup shows all pages (including drafts), doh sometime I think this project piace of.. bag of wonders

**Comment by bashu** [comment]
using ``limit_choices_to`` on ``SimpleRawIdWidget`` can solve that

**Comment by vdboor** [comment]
This is an issue with django-fluent-pages, so it's the right place to add the bug :)

The field type is registered to django-any-urlfield in `fluent_pages/models/__init__.py`
